version: '3.8'

services:
  app:
    container_name: memorygraph_backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./server:/app
    environment:
      - PYTHONUNBUFFERED=1
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - chromadb

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
      - ui
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma
    environment:
      - ALLOW_RESET=true
      - IS_PERSISTENT=true
      - ANONYMIZED_TELEMETRY=false
      - PERSIST_DIRECTORY=/chroma
    networks:
      - app-network
    restart: unless-stopped

  ui:
    container_name: memorygraph_ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  nginx_data:
  memorygraph_backend_data:
  chroma_data:

networks:
  app-network:
    driver: bridge 