version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=www.memorygraph.alenkoikkara.com
      - LETSENCRYPT_HOST=www.memorygraph.alenkoikkara.com

networks:
  app-network:
    driver: bridge 