name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Set up QEMU (for arm64 cross-compilation)
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/arm64
        tags: |
          ghcr.io/alenkoikkara/memento-backend:latest
          ghcr.io/alenkoikkara/memento-backend:${{ github.sha }}
    
        
    # - name: Deploy to ECS
    #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
    #   with:
    #     task-definition: server/task-definition.json
    #     service: memento-backend-service
    #     cluster: memento-cluster
    #     wait-for-service-stability: true 