name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/alenkoikkara/memento-backend:latest
          ghcr.io/alenkoikkara/memento-backend:${{ github.sha }}

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Pull latest backend image and restart container on Pi
      run: |
        ssh -o StrictHostKeyChecking=no charlie@10.0.0.94 << 'EOF'
          cd /home/charlie  # your actual path
          docker compose pull memento-backend
          docker compose up -d --force-recreate --no-deps memento-backend
        EOF
