name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - '.github/workflows/backend.yml'
    tags:
      - 'v*'
  pull_request:
    branches: [main]
    paths:
      - 'server/**'
      - '.github/workflows/backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION="${GITHUB_REF#refs/tags/}"
        else
          VERSION="dev-${GITHUB_SHA::7}"
        fi
        echo "VERSION=$VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Dockerfile
        push: true
        platforms: ${{ startsWith(github.ref, 'refs/tags/') && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: |
          ghcr.io/alenkoikkara/memento-backend:latest
          ghcr.io/alenkoikkara/memento-backend:${{ steps.get_version.outputs.version }}
          ghcr.io/alenkoikkara/memento-backend:${{ github.sha }}

    - name: Cache cloudflared
      id: cache-cloudflared
      uses: actions/cache@v4
      with:
        path: ~/.cloudflared
        key: cloudflared-${{ runner.os }}

    - name: Install cloudflared
      if: steps.cache-cloudflared.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.cloudflared
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o ~/.cloudflared/cloudflared
        chmod +x ~/.cloudflared/cloudflared

    - name: Move cloudflared to PATH
      run: sudo cp ~/.cloudflared/cloudflared /usr/local/bin/cloudflared

    - name: Setup SSH Key and Config
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        ssh-keyscan -H sshpi.alenkoikkara.com >> ~/.ssh/known_hosts

        cat <<EOF > ~/.ssh/config
        Host sshpi
          User charlie
          HostName sshpi.alenkoikkara.com
          IdentityFile ~/.ssh/id_rsa
          ProxyCommand cloudflared access tcp --hostname %h
        EOF

    - name: Restart backend on Pi
      run: |
        ssh sshpi <<'EOF'
          cd /home/charlie
          docker compose up -d --no-deps --force-recreate --pull=missing memento-backend
        EOF
