name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
      
    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/memento-backend:${{ github.sha }} -f server/Dockerfile ./server
        docker push ghcr.io/${{ github.repository }}/memento-backend:${{ github.sha }}
        docker tag ghcr.io/${{ github.repository }}/memento-backend:${{ github.sha }} ghcr.io/${{ github.repository }}/memento-backend:latest
        docker push ghcr.io/${{ github.repository }}/memento-backend:latest
        
    # - name: Deploy to ECS
    #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
    #   with:
    #     task-definition: server/task-definition.json
    #     service: memento-backend-service
    #     cluster: memento-cluster
    #     wait-for-service-stability: true 