name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ui/**'
      - '.github/workflows/frontend.yml'
    types: [closed]

jobs:
  deploy:
    # Only run on main branch or when PR is merged
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './ui/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build-prod
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}

    - name: Check built UI files
      run: ls -la dist

    - name: Install cloudflared
      run: |
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        chmod +x cloudflared
        sudo mv cloudflared /usr/local/bin/

    - name: Setup SSH Key and Config
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat <<EOF > ~/.ssh/config
        Host sshpi
          HostName sshpi.alenkoikkara.com
          User charlie
          IdentityFile ~/.ssh/id_rsa
          ProxyCommand cloudflared access tcp --hostname %h
          StrictHostKeyChecking no
        EOF

    - name: Upload build via SCP manually
      run: |
        scp -r dist/** sshpi:/home/charlie/docker-data/memento/ui
    
    
